export const REFRESH_TOKEN_REPOSITORY = Symbol('REFRESH_TOKEN_REPOSITORY');
export const PASSWORD_RESET_OTP_REPOSITORY = Symbol('PASSWORD_RESET_OTP_REPOSITORY');
export const AUTH_USER_PORT = Symbol('AUTH_USER_PORT');
